import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "@/styles/globals.css";
import HeaderWrapper from "@/components/common/Header/HeaderWrapper";
import Footer from "@/components/common/Footer/Footer";
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

const iranyekan = localFont({
  src: [
    {
      path: "../../assets/Fonts/IRANYekan-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/Fonts/IRANYekan-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../assets/Fonts/IRANYekan-ExtraBlack.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-iranyekan",
  display: "swap",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
      suppressHydrationWarning
      // ${geistSans.variable} ${geistMono.variable}
        className={` ${iranyekan.className} antialiased`}   
      >  
        <HeaderWrapper/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
