import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import AdminOptions from "@/components/Admin/AdminOptions";
<meta name="viewport" content="width=device-width, initial-scale=1.0" />;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-custom-svg">
      <div className=" flex flex-row gap-10 container mx-auto ">
        <AdminOptions />
        {children}
      </div>
    </div>
  );
}
