// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "@/styles/globals.css";
// import AdminOptions from "@/components/Admin/AdminOptions";
// <meta name="viewport" content="width=device-width, initial-scale=1.0" />;

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div className="bg-custom-svg">
//       <div className=" flex flex-row gap-10 container mx-auto ">
//         <AdminOptions />
//         {children}
//       </div>
//     </div>
//   );
// }

// "use client";

// import React, { useState } from "react";
// import AdminOptions from "@/components/Admin/AdminOptions";
// import { HiMenuAlt3 } from "react-icons/hi";

// export default function AdminLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const [sidebarOpen, setSidebarOpen] = useState(false);

//   return (
//     <div className="flex flex-row-reverse min-h-screen bg-custom-svg rtl">
//       {/* Sidebar */}
//       <div
//         className={`fixed lg:relative z-50 h-full bg-background rounded-[20px] shadow p-4 transition-all duration-300 ${
//           sidebarOpen ? "right-0 w-64" : "-right-64 w-64"
//         } lg:right-0 lg:w-80`}
//       >
//         <AdminOptions onNavigate={() => setSidebarOpen(false)} />
//       </div>

//       {/* Backdrop for mobile */}
//       {sidebarOpen && (
//         <div
//           className="fixed inset-0 bg-black/30 z-40 lg:hidden"
//           onClick={() => setSidebarOpen(false)}
//         />
//       )}

//       {/* Main content */}
//       <div className="flex-1 p-4 lg:p-6 lg:mr-80 flex flex-col items-center">
//         {/* Mobile Hamburger */}
//         <div className="lg:hidden mb-4 self-start">
//           <HiMenuAlt3
//             className="w-8 h-8 cursor-pointer text-secondary"
//             onClick={() => setSidebarOpen(true)}
//           />
//         </div>

//         <div className="w-full">{children}</div>
//       </div>
//     </div>
//   );
// }

"use client";

import React, { useState } from "react";
import AdminOptions from "@/components/Admin/AdminOptions";
import { HiMenuAlt3 } from "react-icons/hi";

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <div className="w-full bg-custom-svg ">
      <div className="flex min-h-screen container mx-auto rtl">
        {/* Sidebar */}
        <div
          className={`fixed z-50 h-184  bg-background rounded-[20px] shadow p-4 transition-all duration-300 
          ${sidebarOpen ? "right-0 w-64 -mt-36 h-full" : "-right-64 w-64"} 
          lg:relative lg:right-0 lg:w-80`}
        >
          <AdminOptions onNavigate={() => setSidebarOpen(false)} />
        </div>

        {/* Backdrop for mobile */}
        {sidebarOpen && (
          <div
            className="fixed inset-0 bg-black/30 z-40 lg:hidden "
            onClick={() => setSidebarOpen(false)}
          />
        )}

        {/* Main content */}
        <div className="flex-1 p-4 lg:p-6 lg:ml-0 flex flex-col items-center -mt-12">
          {/* Mobile Hamburger */}
          <div className="lg:hidden mb-4 self-start">
            <HiMenuAlt3
              className="w-8 h-8 cursor-pointer text-secondary"
              onClick={() => setSidebarOpen(true)}
            />
          </div>

          <div className="w-full">{children}</div>
        </div>
      </div>
    </div>
  );
}
